services:
  app:
    build:
      context: ./../../
      dockerfile: ./docker/prod/Dockerfile
      args:
        NEXT_PUBLIC_APP_ENV: ${NEXT_PUBLIC_APP_ENV}
        NEXT_PUBLIC_BACKEND_API_URL: ${NEXT_PUBLIC_BACKEND_API_URL}
        NEXT_PUBLIC_REVERB_APP_KEY: ${NEXT_PUBLIC_REVERB_APP_KEY}
        NEXT_PUBLIC_REVERB_HOST: ${NEXT_PUBLIC_REVERB_HOST}
        NEXT_PUBLIC_REVERB_PORT: ${NEXT_PUBLIC_REVERB_PORT}
        NEXT_PUBLIC_REVERB_SCHEME: ${NEXT_PUBLIC_REVERB_SCHEME}
    restart: always
    ports:
      - 3000:3000
